# Generated by Django 5.2.8 on 2026-07-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0021_poll_option_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField(max_length=300)),
            ],
        ),
    ]
